style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  ReturnCount:
    active: false
naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
complexity:
  LongParameterList:
    functionThreshold: 10
    ignoreDefaultParameters: true
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    active: false
  TooManyFunctions:
    active: false

